trigger:
  - master

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        pool:
          name: 'DuoPrice'  # Use the name of your self-hosted agent pool here
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              echo "Checking Node.js and npm versions..."
              node --version
              npm --version
            displayName: 'Check Node.js and npm versions'

          - script: |
              echo "Current directory:"
              cd
              echo "Files in directory:"
              dir
            displayName: 'Debug Environment'

          - task: Npm@1
            inputs:
              command: 'install'
            displayName: 'npm install'

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
            displayName: 'npm run build'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy Job'
        pool:
          name: 'DuoPrice'  # Use the name of your self-hosted agent pool here
        steps:
          - script: |
              echo "Deploying the DuoPrice application..."
              
              # Debug the build output directory
              echo "Build directory contents:"
              dir build

              # Copy files
              if exist "build\*" (
                echo "Copying files..."
                xcopy /E /I /Y build\* C:\path\to\deployment\directory\
              ) else (
                echo "No files found in the build directory."
              )

              # Check for service existence
              echo "Checking if the service exists..."
              sc query duo-price-service
              if %ERRORLEVEL% NEQ 0 (
                echo "Service not found, skipping restart."
              ) else (
                echo "Stopping service..."
                sc stop duo-price-service
                echo "Starting service..."
                sc start duo-price-service
              )
            displayName: 'Deploy DuoPrice Application'
