# .azure-pipelines.yml
trigger:
- master  # Replace 'main' with your branch name if different

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version you want to use

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- script: |
    npm test
  displayName: 'Run tests'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'  # Replace 'build' with the directory containing your build artifacts if different
    targetFolder: '$(Build.ArtifactStagingDirectory)/webapp'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/webapp'
    artifactName: 'webapp'
    publishLocation: 'Container'
