trigger:
  - master

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        pool:
          name: 'DuoPricing'  # Use the name of your self-hosted agent pool here
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            inputs:
              command: 'install'
            displayName: 'npm install'

          - task: Npm@1
            inputs:
              command: 'run'
              arguments: 'build'
            displayName: 'npm run build'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy Job'
        pool:
          name: 'DuoPricing'  # Use the name of your self-hosted agent pool here
        steps:
          - script: |
              echo "Deploying the application..."
              # Add your deployment script here
            displayName: 'Deploy Application'
