trigger:
  - master

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        pool:
          name: 'DuoPrice'  # Updated agent pool name
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            inputs:
              command: 'install'
            displayName: 'npm install'

          - task: Npm@1
            inputs:
              command: 'run'
              arguments: 'build'
            displayName: 'npm run build'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy Job'
        pool:
          name: 'DuoPrice'  # Updated agent pool name
        steps:
          - script: |
              echo "Deploying the DuoPrice application..."
              # Example deployment script (customize as needed)
              # Assuming deployment involves copying files and restarting services
              # Replace with your actual deployment commands
              cp -r build/* /path/to/deployment/directory/
              # Restart application service if needed
              systemctl restart duo-price-service
            displayName: 'Deploy DuoPrice Application'
